// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FormTest$RescriptTypeInferenceExample from "./FormTest.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: "flex justify-center items-center h-screen"
            }, "ReScript React with Tailwind running on Vite", React.createElement(FormTest$RescriptTypeInferenceExample.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
