// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Formik from "formik";

function FormTest(Props) {
  var initialValues = {
    name: "",
    description: ""
  };
  var onSubmit = function (values) {
    console.log(values);
    
  };
  Curry._1(Formik.useFormik, {
        initialValues: initialValues,
        onSubmit: onSubmit
      });
  return React.createElement("div", undefined, "Formik Test");
}

var make = FormTest;

export {
  make ,
  
}
/* react Not a pure module */
