// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function FormTest(Props) {
  return React.createElement("div", undefined, "Formik Test");
}

var make = FormTest;

export {
  make ,
  
}
/* react Not a pure module */
